name: bw_pinentry
description: A pinentry wrapper around the bitwarden CLI to use your vault for GPG-Key storage.
version: 1.0.0
repository: https://github.com/Skycoder42/bw-pinentry
publish_to: none

environment:
  sdk: ^3.7.0

platforms:
  linux:

dependencies:
  async: ^2.13.0
  freezed_annotation: ^2.4.4
  meta: ^1.16.0
  stream_channel: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  dart_pre_commit: ^5.4.3
  dart_test_tools: ^6.1.0
  freezed: ^2.5.8

dart_pre_commit:
  flutter-compat: false
