name: bw_pinentry
description: A pinentry wrapper around the bitwarden CLI to use your vault for GPG-Key storage.
version: 1.0.4
repository: https://github.com/Skycoder42/bw-pinentry
publish_to: none

environment:
  sdk: ^3.10.0

platforms:
  linux:

executables:
  bw-pinentry: bw_pinentry

dependencies:
  async: ^2.13.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meta: ^1.17.0
  stream_channel: ^2.1.4

dev_dependencies:
  build_runner: ^2.10.4
  dart_pre_commit: ^6.1.0
  dart_test_tools: ^7.0.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  pkgname: bw-pinentry
  license: BSD
  depends:
    - pinentry
    - bitwarden-cli

cider:
  link_template:
    tag: https://github.com/Skycoder42/bw-pinentry/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/bw-pinentry/compare/v%from%...v%to%

dart_pre_commit:
  flutter-compat: false
